package ru.hse.plugin.ui;

import ru.hse.plugin.core.entities.PropertyEntity;

import javax.swing.*;
import java.awt.*;

public class PropertyUIItem {
    private JCheckBox checkbox;
    private JPanel panel1;
    PropertyEntity propertyEntity;

    public PropertyUIItem(PropertyEntity propertyEntity) {
        this.propertyEntity = propertyEntity;
        checkbox.setText(propertyEntity.getName());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        checkbox = new JCheckBox();
        checkbox.setHorizontalAlignment(2);
        checkbox.setHorizontalTextPosition(4);
        checkbox.setText("CheckBox");
        panel1.add(checkbox);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
